import type { Subject, Fact } from './types';
const f = (id: string, name: string, emoji: string, lv: number, text: string): Fact => ({ id, name, emoji, lv, text });
// lv: 1 = easy, 2 = medium, 3 = hard (4 facts each)
export const SUBJECTS: Subject[] = [
{ id:'science', name:'Science', emoji:'🪐', color:'#7c3aed', intro:'Explore the Sun, the planets and our solar system!',
  facts:[
   f('sun','Sun','☀️',1,'The Sun is a star. It gives us light and warmth!'),
   f('earth','Earth','🌍',1,'Our home, the only planet we know with life!'),
   f('mars','Mars','🔴',1,'The Red Planet has the tallest volcano in the solar system.'),
   f('jupiter','Jupiter','🌪️',1,'The biggest planet. Its Great Red Spot is a giant storm.'),
   f('mercury','Mercury','🪨',2,'The smallest planet. A year here lasts only 88 days!'),
   f('venus','Venus','☁️',2,'The hottest planet, wrapped in thick clouds.'),
   f('saturn','Saturn','💍',2,'Famous for its rings made of ice and rock.'),
   f('magnet','Magnet','🧲',2,'Pulls on iron and steel. Every magnet has a north and a south pole.'),
   f('volcano','Volcano','🌋',3,'A mountain where melted rock, called lava, bursts out from inside Earth.'),
   f('rainbow','Rainbow','🌈',3,'Sunlight splits into colors as it passes through raindrops.'),
   f('electricity','Electricity','⚡',3,'A flow of tiny charges that powers lights and machines.'),
   f('echo','Echo','🗣️',3,'Sound that bounces off a surface and comes back to you.')],
  quiz:[{q:'Which planet is known as the Red Planet?',options:['Venus','Mars','Jupiter'],answer:1},
        {q:'What does the Sun give us?',options:['Light and warmth','Rain','Wind'],answer:0}] },
{ id:'chemistry', name:'Chemistry', emoji:'⚗️', color:'#ef4444', intro:'Atoms and molecules are the tiny pieces of everything!',
  facts:[
   f('water','Water (H₂O)','💧',1,'Two hydrogen atoms and one oxygen atom. Water is essential for life!'),
   f('oxygen','Oxygen','🌬️',1,'The gas in the air that we need to breathe.'),
   f('co2','Carbon dioxide (CO₂)','🌫️',1,'We breathe it out and plants use it to make food.'),
   f('ice','Ice','🧊',1,'Water that got so cold it turned into a solid.'),
   f('methane','Methane (CH₄)','🔥',2,'One carbon atom with four hydrogens, a gas used in stoves.'),
   f('salt','Salt','🧂',2,'A crystal made of two elements joined together: sodium and chlorine.'),
   f('acid','Acid','🍋',2,'Lemon juice is a mild acid. Acids taste sour.'),
   f('rust','Rust','🔩',2,'Iron slowly turns orange-brown when it meets water and air.'),
   f('atom','Atom','⚛️',3,'The tiny building block of everything, far too small to see.'),
   f('element','Element','🧪',3,'A pure substance made of one kind of atom, like gold or oxygen.'),
   f('molecule','Molecule','🔗',3,'Two or more atoms joined together.'),
   f('reaction','Reaction','💥',3,'When substances change into new ones, like a cake baking in the oven.')],
  quiz:[{q:'How many hydrogen atoms are in water?',options:['1','2','3'],answer:1},
        {q:'Which gas do plants use to make food?',options:['Methane','Oxygen','Carbon dioxide'],answer:2}] },
{ id:'math', name:'Math', emoji:'📐', color:'#0ea5e9', intro:'Play with numbers, shapes and puzzles!',
  facts:[
   f('cube','Cube','🧊',1,'6 faces, 12 edges, 8 corners. Dice are cubes!'),
   f('sphere','Sphere','⚽',1,'Perfectly round: no edges and no corners.'),
   f('cone','Cone','🍦',1,'1 flat face, 1 curved surface and 1 pointy corner.'),
   f('cylinder','Cylinder','🥫',1,'2 flat circles and 1 curved side, like a can.'),
   f('pyramid','Square pyramid','🔺',2,'5 faces, 8 edges and 5 corners.'),
   f('triangle','Triangle','📐',2,'A flat shape with 3 sides and 3 corners.'),
   f('circle','Circle','⭕',2,'A round shape with no corners. Every point is the same distance from the center.'),
   f('fraction','Fraction','🍕',2,'A part of a whole, like 1/4 of a pizza.'),
   f('perimeter','Perimeter','📏',3,'The distance all the way around the edge of a shape.'),
   f('area','Area','🟦',3,'How much flat space a shape covers.'),
   f('zero','Zero','0️⃣',3,'The number that means nothing, and it makes big numbers like 100 possible.'),
   f('pi','Pi','🥧',3,'About 3.14. It is the distance around a circle divided by the distance across it.')],
  quiz:[{q:'How many faces does a cube have?',options:['4','6','8'],answer:1},
        {q:'Which shape has no corners?',options:['Sphere','Cube','Pyramid'],answer:0}] },
];
export const getSubject = (id: string) => SUBJECTS.find(s => s.id === id);
